name: Manual Running Tests

on:
  workflow_dispatch:
    inputs:
      skip-tests:
        description: 'Skip running tests?'
        required: false
        type: boolean
        default: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven  # Кэширует зависимости Maven для ускорения последующих запусков

      - name: Run Maven tests
        if: ${{ !inputs.skip-tests }}
#        run: mvn --batch-mode test
        run: mvn clean test
